
// var x=30;
// let y=40;
// const z=50;

// if(x===30)
// {
//     console.log("matched");
// }

// for(i=0;i<=10;i++)
// {
//     console.log(i);
// }

// const arr=[2,5,7,9,8,12,15,17];
// console.log(arr);

// const app=require('./app')
// console.log(app.z());

// const arr=[2,5,7,9,8,12,15,8,17,8];
// let result = arr.filter((item)=>{
//     return item===8
// })
// console.warn(result)

// const fs = require('fs');
// fs.writeFileSync('data.txt','Hello world this file is auto generated by index.js')
// const pr=require('fs').writeFileSync;
// pr('xyz.txt','CODjkffrejE')

var http = require('http');
// http.createServer((req,resp)=>{
//     resp.write("<h1>hello this is Prince Kumar Yadav</h1>");
//     resp.end();
// }).listen(5500);

function dataControl(req,resp)
{
    resp.write("<h1>hello this is Prince Kumar Yadav</h1>");
    resp.write("<h2>hello this is Prince Kumar Yadav</h2>");
    resp.write("<h3>hello this is Prince Kumar Yadav</h3>");
    resp.write("<h4>hello this is Prince Kumar Yadav</h4>");
    resp.write("<h5>hello this is Prince Kumar Yadav</h5>");
    resp.write("<h6>hello this is Prince Kumar Yadav</h6>");
    resp.end();
}
http.createServer(dataControl).listen(4500);